sequenceDiagram
    participant B as Bootstrap (Host)
    participant M as main.ts (Node.js)
    participant K as Kernel.ts (Core)
    participant V as VFS (system.db)
    participant I as /bin/init.ts (PID 1)
    participant S as /bin/tsh.ts (User Shell)

    Note over B: bootstrap.bat / .sh
    B->>M: node src/main.ts
    
    activate M
    M->>K: new Kernel()
    M->>K: kernel.boot()
    
    activate K
    K->>V: Connect & Init Schema
    
    Note right of K: VFS sudah di-sync dari host
    via install / vfs-bootstrap (script)
    
    K->>K: Init HAL & Subsystems
    K-->>M: Boot Completed
    deactivate K
    
    M->>K: kernel.runInit()
    activate K
    K->>I: spawn process (PID 1)
    deactivate K
    deactivate M
    
    activate I
    I->>I: Run /etc/rc.local.ts
    I->>I: Start Getty/Login on TTYs
    
    I->>S: exec /bin/tsh.ts (after login)
    activate S
    Note over S: User Session Active
    deactivate I